### register user
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Rudi Kurniawan",
  "email": "rudikurniawan503@gmail.com",
  "password": "kurniawan",
  "passwordConfirmation": "kurniawan"
}

### login user 
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "rudikurniawan505@gmail.com",
  "password": "kurniawa"
}