### register user
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Rudi Kurniawan",
  "email": "rudikurniawan501gmail.com",
  "password": "kurniawan",
  "passwordConfirmation": "kurniawa"
}